import type { Locale } from "@/lib/i18n/config";

export type LegalPageKind = "privacy" | "terms" | "accessibility";
type Section = { title: string; paragraphs: string[] };

// Server-rendered copy: do not import this full document into client controls.
export const legalContent: Record<Locale, Record<LegalPageKind, Section[]>> = {
  he: {
    privacy: [
      { title: "מה השירות עושה", paragraphs: ["MortgageMentor מאפשר לבצע סימולציות משכנתא, ללמוד מושגים ולשמור ולהשוות תמהילים. מדיניות זו מתארת את המידע המעובד במסגרת השירות ואת האפשרויות העומדות לרשותך."] },
      { title: "איזה מידע מעובד ולשם מה", paragraphs: ["בעת גלישה, שרתי האתר וספקי התשתית עשויים לעבד כתובת IP, פרטי דפדפן ומכשיר, כתובות עמודים, זמני בקשות ושגיאות, לצורך אספקת השירות, אבטחה וטיפול בתקלות. נתוני החישוב עשויים להופיע בכתובת העמוד ולהישלח לשרת בעת פתיחתו או עדכונו; שימוש ללא חשבון אינו מבטיח אנונימיות.", "בהתחברות דרך Google מתקבלים פרטי זיהוי בסיסיים, כגון מזהה משתמש, כתובת אימייל, שם ותמונת פרופיל, ונשמרים פרטי חשבון ומועדי התחברות. פרטים אלה משמשים לזיהוי ולניהול הגישה לתמהילים. איננו מבקשים את סיסמת Google שלך או גישה לדואר ולאנשי הקשר.", "בעת שמירה נשמרים שם התמהיל, סכומים, ריביות, תקופות, סוגי מסלולים, שיטות החזר, הנחות ותחזיות, תוצאות החישוב ומועדיו, כשהם משויכים לחשבונך. המידע נועד להצגת תמהילים שמורים, עריכתם והשוואתם. אין צורך להזין מספר תעודת זהות, מספר חשבון בנק או מסמכי בנק."] },
      { title: "מסירת מידע היא לבחירתך", paragraphs: ["אין חובה חוקית למסור לנו את פרטי החשבון והתמהיל. אפשר להשתמש במחשבון בלי להתחבר. בלי התחברות לא ניתן לשמור תמהילים בחשבון; בלי הנתונים הדרושים לחישוב לא ניתן לחשב את התוצאה המבוקשת. שמירה בחשבון נעשית ביוזמתך באמצעות פעולת שמירה."] },
      { title: "ספקים וגישה למידע", paragraphs: ["Google מספקת את ההזדהות; Supabase מספקת שירותי חשבון ומסד נתונים; Vercel מספקת אירוח ותפעול האתר. ספקים אלה מעבדים מידע הנחוץ לשירותיהם, בכפוף להסדרים ולמדיניות שלהם, והעיבוד עשוי להתבצע מחוץ לישראל.", "תמהילים שמורים מוגנים באמצעות בדיקת חשבון והרשאות גישה. מסך הניהול מציג למנהל מורשה פרטי משתמשים, מועדי התחברות, מספר שמורים ומועד עדכון אחרון, לצורכי תפעול ותמיכה; תוכן התמהילים אינו מוצג בו. נתוני התמהילים עדיין נשמרים במסד הנתונים לצורך השירות, ואין להסיק שהם מוסתרים ממפעיל התשתית. מידע עשוי להימסר גם אם הדבר נדרש על פי דין או צו מחייב."] },
      { title: "עוגיות", paragraphs: ["האתר משתמש בעוגיות לצורכי התחברות, המשכיות הזיהוי ואבטחתו. חסימתן עשויה למנוע התחברות ושמירת תמהילים. ניתן לנהל או למחוק עוגיות בהגדרות הדפדפן ולהתנתק דרך תפריט החשבון. בקוד האתר הנוכחי לא הוטמעו כלי פרסום או מעקב שיווקי. אם יתווספו שימושים כאלה, יש לעדכן את ההודעה ולהסדיר הסכמה ככל שנדרשת לפני הפעלתם."] },
      { title: "קישורי שיתוף וקובצי PDF", paragraphs: ["קישור למחשבון יכול להכיל את נתוני התמהיל והנחות החישוב. מי שמקבל את הקישור יכול לפתוח ולקרוא את הנתונים גם בלי חשבון. הקישור עשוי להישמר בהיסטוריית הדפדפן ובשירות שבו שותף; מחיקת תמהיל שמור אינה מוחקת עותקי קישורים או קבצים שכבר נשלחו. קישורים לעמודי שמורים והשוואת שמורים דורשים הרשאת חשבון.", "שמירת סיכום כ־PDF נעשית דרך הדפדפן. הקובץ כולל נתוני חישוב; לאחר הורדתו האחריות לבחירת מקום השמירה והנמענים היא שלך. הימנע משיתוף מידע אישי שאינך רוצה לחשוף."] },
      { title: "שמירה, עיון, תיקון ומחיקה", paragraphs: ["תמהילים נשמרים בחשבון עד למחיקתם על ידך או במסגרת טיפול בחשבון. אפשר להציג, לערוך ולמחוק תמהילים במסך שמורים. עותקים במערכות גיבוי ורישומי תפעול עשויים להישאר לתקופות נוספות בהתאם להסדרי הספקים ולחובות הדין; מחיקה מהממשק אינה הבטחה למחיקה מיידית מכל גיבוי.", "אפשר לפנות לפרטי הקשר המופיעים בעמוד זה בבקשה לעיין במידע אישי עליך, לתקנו, או לבקש מחיקה כאשר המידע אינו נכון, שלם, ברור או מעודכן, בהתאם לדין. ניתן גם לבקש סגירת חשבון ומחיקת המידע המשויך אליו; היקף הטיפול כפוף לחובות שמירה ולזכויות לפי דין. ייתכן שנצטרך לאמת את זהותך באופן מידתי. אין לשלוח סיסמאות או מסמכים רגישים בפנייה הראשונית."] },
      { title: "אבטחה ושינויים", paragraphs: ["האתר משתמש בחיבור מוצפן ובמנגנוני אימות והרשאות. אף מערכת אינה חסינה לחלוטין מתקלות או מגישה בלתי מורשית. אם זיהית חשש לחשיפה, פנה למפעיל בלי לצרף מידע של משתמשים אחרים. שינויים מהותיים בשימוש במידע יוצגו באופן מתאים, ובמידת הצורך תתבקש הסכמה נוספת. התאריך בראש העמוד מציין את גרסת המדיניות."] },
    ],
    terms: [
      { title: "שירות חינמי", paragraphs: ["השימוש ב־MortgageMentor ובכל השירותים הזמינים בו הוא חינמי לחלוטין. אין דמי מנוי או תשלום עבור חישובים, שמירת תמהילים, השוואה או הפקת סיכום. אם יוצע בעתיד שירות בתשלום, המחיר והתנאים יוצגו מראש ותידרש הסכמה מפורשת לפני חיוב."] },
      { title: "מטרת האתר", paragraphs: ["MortgageMentor הוא כלי ללמידה, סימולציה והשוואה בין תרחישי משכנתא. התוכן והתוצאות אינם ייעוץ משכנתאות, השקעות, מס או ייעוץ משפטי אישי, אינם המלצה לקחת הלוואה ואינם אישור אשראי או הצעה מחייבת. לפני החלטה כספית יש לבדוק הצעה כתובה מהבנק ולפנות לאיש מקצוע מתאים לפי הצורך."] },
      { title: "חישובים ותחזיות", paragraphs: ["התוצאות תלויות בנתונים ובהנחות שהוזנו, בשיטת החישוב ובמקורות הזמינים במועד החישוב. ריבית עתידית, מדד, עוגנים והחזרים במסלולים משתנים או צמודים הם תחזיות, ועשויים להתפתח אחרת בפועל. סימון רכיב כקבוע מתייחס למודל ובהנחה שנתוני ההלוואה אינם משתנים; הוא אינו התחייבות של בנק.", "נתוני בנק ישראל והלשכה המרכזית לסטטיסטיקה, כאשר הם מוצגים, משמשים מקורות מידע בלבד. האתר אינו שייך להם, אינו פועל מטעמם ואין בשימוש בנתוניהם משום אישור למחשבון. ייתכנו עיכובי עדכון, נתוני גיבוי, הבדלי עיגול ושיטות חישוב בין בנקים. יש לבדוק את תאריך הנתונים והערות המקור.", "החישוב אינו כולל בהכרח ביטוחים, עמלות, הוצאות נלוות, התאמות לפי ימי תשלום או תנאים פרטניים של הבנק. סכומים, מדדי יציבות, תרחישי לחץ והשוואות אינם הבטחה לתוצאה, לחיסכון או ליכולת החזר. תמהיל שמור וקובץ PDF הם תמונת מצב לפי המועד וההנחות המוצגים."] },
      { title: "חשבון ושימוש סביר", paragraphs: ["יש להזין מידע שאתה רשאי להשתמש בו ולשמור על הגישה לחשבון Google שלך. אין לנסות לגשת לתמהילים של אחרים, לעקוף הרשאות, לשבש את השירות או להעלות מידע בלתי חוקי. במקרה של חשד לשימוש פוגעני ניתן להגביל גישה במידה הנדרשת להגנה על השירות והמשתמשים, בכפוף לדין."] },
      { title: "זמינות, אחריות וזכויות", paragraphs: ["השירות עשוי להשתנות או להיות בלתי זמין עקב תחזוקה, תקלה או תלות בספקים. אין התחייבות לזמינות רציפה או להיעדר שגיאות. מומלץ לשמור עותק של תוצאות חשובות ולדווח על טעות שנתגלתה.", "האחריות לשירות תיקבע לפי הדין החל ונסיבות המקרה. אין בתנאים אלה כדי לשלול זכויות קוגנטיות של משתמש או לפטור את המפעיל מאחריות שלא ניתן להגביל לפי דין. אין התחייבות לפצות או לשפות את המפעיל באופן גורף כתנאי לשימוש.", "מותר להשתמש בתוצאות החישוב האישיות ולשתף אותן. זכויות בתוכן, בעיצוב ובסימני המסחר של האתר או של צדדים שלישיים נשארות בידי בעליהן, בכפוף לשימושים המותרים בדין."] },
      { title: "פרטיות ועדכון התנאים", paragraphs: ["השימוש במידע אישי מוסבר במדיניות הפרטיות, לרבות התחברות, שמירה ושיתוף קישורים. תנאים מעודכנים יוצגו עם תאריך עדכון; שינוי מהותי יובא לידיעת המשתמשים באופן מתאים. על השירות חל הדין הישראלי, בכפוף להוראות מחייבות החלות על המשתמש ולכללי סמכות השיפוט שבדין."] },
    ],
    accessibility: [
      { title: "שימוש נגיש באתר", paragraphs: ["באתר קיימים ממשק בעברית ובאנגלית, רכיבי טופס עם תוויות, ניווט מקלדת ברכיבים שונים וטבלאות המציגות את נתוני החישוב לצד הגרפים. אפשר להשתמש בהגדלת התצוגה של הדפדפן."] },
      { title: "מצב הבדיקה", paragraphs: ["טרם הושלמה בדיקת נגישות מקצועית מלאה של האתר. אין בעמוד זה אישור לעמידה מלאה בתקן או הצהרה על פטור. בפרט, טבלאות רחבות, חלונות שמירה, גרפים ופלט ההדפסה דורשים בדיקה נוספת עם טכנולוגיות מסייעות ובטלפון."] },
      { title: "דיווח ובקשת עזרה", paragraphs: ["נתקלת בקושי? פנה לפרטי הקשר בעמוד זה וציין את העמוד, הפעולה שניסית לבצע, סוג המכשיר והדפדפן, וטכנולוגיה מסייעת אם נעשה בה שימוש. אין צורך לשלוח נתוני משכנתא אישיים. ניתן לבקש סיוע בקבלת התוכן בצורה נגישה."] },
    ],
  },
  en: {
    privacy: [
      { title: "About the service", paragraphs: ["MortgageMentor provides mortgage simulations, educational material, and saved-scenario comparisons. This policy explains the information processed by the service and your choices."] },
      { title: "Information and purposes", paragraphs: ["Our hosting and infrastructure providers may process IP addresses, browser and device details, requested URLs, timestamps and errors to operate, secure and troubleshoot the service. Calculator inputs can appear in page URLs and reach the server when a page is opened or updated. Using the calculator without an account does not guarantee anonymity.", "Google sign-in provides basic identity details, such as a user identifier, email, name and profile picture. Account and sign-in timestamps are retained to identify you and manage access to saved scenarios. We do not request your Google password, mailbox or contacts.", "Saving a scenario stores its name, amounts, rates, terms, track types, repayment methods, assumptions, forecasts, results and timestamps, linked to your account. This enables viewing, editing and comparing your scenarios. No identity number, bank account number or bank documents are required."] },
      { title: "Your choice", paragraphs: ["You have no legal obligation to provide account or scenario details to us. You may use the calculator without signing in, but account saving requires sign-in. Calculations require the relevant inputs. Saving to an account happens when you initiate a save."] },
      { title: "Providers and access", paragraphs: ["Google provides sign-in, Supabase provides authentication and database services, and Vercel hosts the website. These providers process information required for their services under their respective arrangements and policies; processing may take place outside Israel.", "Account checks and access permissions protect saved scenarios. The administration screen displays user details, sign-in dates, saved-scenario counts and the last saved update for operation and support; it does not display scenario contents. Scenario data remains in the database to provide the service and should not be considered hidden from the infrastructure operator. Information may also be disclosed where required by law or a binding order."] },
      { title: "Cookies", paragraphs: ["Cookies support sign-in, session continuity and security. Blocking them may prevent sign-in and account saving. You can manage cookies in your browser and sign out through the account menu. The current website code does not integrate advertising or marketing trackers. Any future such use must be disclosed and, where required, consent obtained before activation."] },
      { title: "Shared links and PDFs", paragraphs: ["Calculator links can contain scenario inputs and assumptions. Anyone receiving a calculator link can view them without an account. Links may remain in browser history or the services used to share them. Deleting a saved scenario does not erase links or files already shared. Saved-scenario and saved-comparison pages require account authorization.", "PDF summaries are saved through your browser and contain calculation details. Choose their storage location and recipients carefully; avoid sharing personal information you do not want exposed."] },
      { title: "Retention and your requests", paragraphs: ["Scenarios remain in your account until you delete them or they are removed as part of account handling. You can view, edit and delete scenarios in Saved. Backups and operational logs may persist for additional periods under provider arrangements and legal obligations. Deletion from the interface does not promise immediate erasure from every backup.", "Contact the operator listed on this page to request access to your personal information, correction, or deletion of information that is inaccurate, incomplete, unclear or outdated, in accordance with applicable law. You may also request account closure and deletion of associated information, subject to legal retention duties and rights. Proportionate identity verification may be required. Do not include passwords or sensitive documents in your initial message."] },
      { title: "Security and changes", paragraphs: ["The service uses encrypted connections, authentication and access controls. No system is completely immune to failure or unauthorized access. Report suspected exposure without including other users' information. Material changes to information use will be communicated appropriately, with further consent where required. The date above identifies this policy version."] },
    ],
    terms: [
      { title: "Free service", paragraphs: ["MortgageMentor and all services currently available on it are completely free. There are no subscription fees or charges for calculations, saved scenarios, comparisons or summaries. If a paid service is offered in the future, its price and terms will be disclosed in advance and explicit agreement will be required before charging."] },
      { title: "Purpose", paragraphs: ["MortgageMentor is an educational tool for simulating and comparing mortgage scenarios. Its content and results are not personal mortgage, investment, tax or legal advice, a recommendation to borrow, credit approval or a binding offer. Review a written bank offer and seek appropriate professional advice before making a financial decision."] },
      { title: "Calculations and forecasts", paragraphs: ["Results depend on inputs, assumptions, calculation methods and information available at the time. Future interest rates, inflation, anchors and payments on variable or indexed tracks are forecasts and may differ from reality. A fixed label describes the model assuming unchanged loan terms; it is not a bank commitment.", "Bank of Israel and Central Bureau of Statistics data, where shown, are information sources. This service is not affiliated with or endorsed by those institutions. Updates may be delayed, fallback data may be used, and banks may use different rounding or calculation methods. Check source dates and notes.", "Calculations may omit insurance, fees, other expenses, payment-day adjustments or individual bank terms. Stability indicators, stress scenarios and comparisons do not guarantee outcomes, savings or affordability. Saved scenarios and PDFs reflect the dates and assumptions shown."] },
      { title: "Accounts and reasonable use", paragraphs: ["Use only information you are entitled to use and protect access to your Google account. Do not access other users' scenarios, bypass permissions, disrupt the service or submit unlawful information. Access may be restricted as necessary to protect the service and users from suspected abuse, subject to applicable law."] },
      { title: "Availability, responsibility and rights", paragraphs: ["The service may change or become unavailable due to maintenance, failures or third-party dependencies. Continuous availability and error-free results are not guaranteed. Keep copies of important calculations and report errors.", "Responsibility is determined by applicable law and the circumstances. These terms do not waive mandatory user rights or exclude liability that cannot lawfully be excluded. Using the site does not impose a blanket obligation to indemnify the operator.", "You may use and share your own calculation results. Rights in website content, design and third-party trademarks remain with their respective owners, subject to uses permitted by law."] },
      { title: "Privacy and updates", paragraphs: ["The privacy policy explains sign-in, saving and shared links. Updated terms will display a revision date, and material changes will be communicated appropriately. Israeli law governs the service, subject to mandatory laws protecting the user and applicable jurisdiction rules."] },
    ],
    accessibility: [
      { title: "Using the site", paragraphs: ["The site provides Hebrew and English interfaces, labelled form controls, keyboard navigation in various components, and tables alongside calculation charts. Browser zoom can be used."] },
      { title: "Review status", paragraphs: ["A full professional accessibility assessment has not yet been completed. This page is not certification of full standards compliance or a declaration of exemption. Wide tables, save dialogs, charts and printed output need further review with assistive technology and on phones."] },
      { title: "Request assistance", paragraphs: ["Contact the operator listed on this page and describe the page, attempted action, device, browser and assistive technology if relevant. You do not need to send personal mortgage details. You may request assistance accessing the content in an accessible format."] },
    ],
  },
};
