import { describe, expect, it } from "vitest";
import { isIsraeliBankingDay, israelIsoDate, nextIsraeliBusinessDay } from "../israeli-banking-calendar";

describe("BOI banking calendar", () => {
  // Independently transcribed closed dates, not generated by the implementation.
  // https://www.boi.org.il/media/py1hwkw3/zahav-holidays-2026-heb.pdf
  // https://www.boi.org.il/media/35olzmy2/zahav-holidays-2027-heb.pdf
  // Election closure supplements the annual calendar:
  // https://embassies.gov.il/saopaulo/he/announcements/vote10-2026
  it.each([
    [2026, ["03-03", "04-02", "04-08", "04-22", "05-22", "07-23", "09-12", "09-13", "09-20", "09-21", "09-26", "10-03", "10-27"]],
    [2027, ["03-23", "04-22", "04-28", "05-12", "06-11", "08-12", "10-02", "10-03", "10-10", "10-11", "10-16", "10-23"]],
  ] as const)("matches every date in the %i official calendar", (year, holidays) => {
    const closures = new Set<string>(holidays);
    for (let date = new Date(Date.UTC(year, 0, 1)); date.getUTCFullYear() === year; date.setUTCDate(date.getUTCDate() + 1)) {
      const iso = date.toISOString().slice(0, 10);
      expect(isIsraeliBankingDay(iso), iso).toBe(date.getUTCDay() !== 6 && !closures.has(iso.slice(5)));
    }
  });

  it.each([
    ["2026-09-17", "2026-09-18"],
    ["2026-09-18", "2026-09-22"], // Saturday, Yom Kippur eve, Yom Kippur
    ["2026-04-01", "2026-04-03"],
    ["2026-07-22", "2026-07-24"],
    ["2026-10-26", "2026-10-28"],
    ["2024-05-13", "2024-05-15"], // postponed Independence Day
    ["2025-04-30", "2025-05-02"], // advanced Independence Day
    ["2022-08-05", "2022-08-08"], // postponed Tisha B'Av
  ])("activates after %s on %s", (published, effective) => {
    expect(nextIsraeliBusinessDay(published)).toBe(effective);
  });

  it.each(["invalid", "2026-02-30", "2026-7-2"])("rejects invalid date %s", (date) => {
    expect(() => nextIsraeliBusinessDay(date)).toThrow(RangeError);
  });

  it("uses Israel midnight in summer and winter, independent of server timezone", () => {
    expect(israelIsoDate(new Date("2026-10-05T20:59:59Z"))).toBe("2026-10-05");
    expect(israelIsoDate(new Date("2026-10-05T21:00:00Z"))).toBe("2026-10-06");
    expect(israelIsoDate(new Date("2026-12-01T21:59:59Z"))).toBe("2026-12-01");
    expect(israelIsoDate(new Date("2026-12-01T22:00:00Z"))).toBe("2026-12-02");
  });
});
